### ISSUE TITLE
Problem with  WidgetsBinding.instance!.addPostFrameCallback((timeStamp), please update and fixed this issue

### ISSUE THREAD

**Issue by Kimsoer** [smartbackme/kg_charts#2]
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/kg_charts-0.0.5/lib/src/flutter_radar_map.dart:508:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^

**Comment by sehoon787** [comment]
This pr could be solution for your problem. https://github.com/smartbackme/kg_charts/pull/3

**Comment by smartbackme** [comment]
solve
